directories:
  output: release-builds
  buildResources: build
appId: com.hamzaak.electron-react-webpack-boilerplate
artifactName: electron-react-webpack-boilerplate-setup-1.0.0.exe
productName: Electron React Webpack Boilerplate
win:
  target:
    - target: nsis
      arch:
        - x64
        - ia32
  icon: public/assets/app.ico
electronVersion: 4.2.12
